In [15]:
import os
import json
import pandas as pd
import ollama
from pydantic import BaseModel
from collections import deque
import time
from concurrent.futures import ThreadPoolExecutor

# Original Data Files

In [85]:
os.getcwd()
script_dir = os.getcwd()
food_file_path = os.path.join(script_dir, 'data\\yelp\\food_photos.json')
business_file_path = os.path.join(script_dir, 'data\\yelp\\business\\yelp_academic_dataset_business.json')
# customer_file_path = os.path.join(script_dir, 'data\\yelp\\business\\yelp_academic_dataset_review.json')

In [86]:
food_df = pd.read_json(food_file_path, lines=True, nrows=3000000)
business_df = pd.read_json(business_file_path, lines=True, nrows=3000000)
# customer_df = pd.read_json(customer_file_path, lines=True)
print("food df has {} rows and uses {} GB".format(food_df.size, food_df.memory_usage() / 1000))
print("business df has {} rows and uses {} GB".format(business_df.size, business_df.memory_usage() / 1000))
# print("customer df has {} rows and uses {} GB".format(customer_df.size, customer_df.memory_usage() / 1000))

food df has 800400 rows and uses Index             0.128
photo_id       1600.800
business_id    1600.800
caption        1600.800
label          1600.800
dtype: float64 GB
business df has 2104844 rows and uses Index              0.128
business_id     1202.768
name            1202.768
address         1202.768
city            1202.768
state           1202.768
postal_code     1202.768
latitude        1202.768
longitude       1202.768
stars           1202.768
review_count    1202.768
is_open         1202.768
attributes      1202.768
categories      1202.768
hours           1202.768
dtype: float64 GB

In [87]:
food_df = food_df.loc[(food_df["label"] == "food") & (food_df["caption"].str.contains(r'[a-zA-Z0-9]', na=False))]
print(f"Food df has {food_df.size} records.")
food_df.loc[food_df['caption'].str.contains("cheese")]

Food df has 221156 records.

,photo_id,business_id,caption,label
554,KYQF6tf8uh5K14_vjjWupg,-cEFKAznWmI0cledNOIQ7w,Ricotta cheesecake,food
691,uxjBwrlOWxtWlrqlYDWu5A,SUARAtRB_3ZcLLcH8f_F9Q,steaks were fantastic!! served with Mac and ch...,food
888,K-HOMnyMN-FpxmefeQLR_w,adb1hOYICrJ1Ix8M0sRpbw,"Greek Bruchetta, spinach and cheese pastries",food
1211,694l-_WpcJA-xBoy-Tv4bg,_OMGZ3TXOfN2By7skat_bw,"Lobster Springroll... Stuffed with lobster, cr...",food
1255,1t21bdiTshnfOowrkOdpnw,EQblMgFRo07lVMGJvfIUtw,Ham and cheese on a kaiser roll,food
...,...,...,...,...
199754,GxsPG9eGtoBEQ4Qlxx16XQ,bc_sQ7tk1y-0vRA0BTcY4g,Caramel cheesecake cookie -- a bestseller!,food
199833,WcQIN1lhkMii0tKxmmFsAQ,oHvEgLH6pAkcrPmeR1l3UQ,Mac and cheese 4/5,food
199860,w2n8bOCO5M6ZI04bQTVk2g,_tt4nysrN8JpzLLVXL-z5A,The cheese plate,food
199911,lrFJLmjUpvfeTYS0GqVWyA,1XoIXcIttDtoDKYnMRHKRQ,QDOBA's signature 3-cheese queso pairs perfect...,food
199979,DdqxVxGRfx5_-Li9vg5PpA,brvQyLy-T9_tcVk7XRJhcA,Naked wings tossed in garlic parmesan served ...,food

In [ ]:
#Shuffle all rows and reset the index, then select only 10000
# food_df = food_df.sample(frac=1, ignore_index=True)
# food_df = food_df.iloc[:3000]

In [90]:
merged_df = food_df.merge(business_df, on="business_id")
merged_df["food"] = merged_df["caption"]
merged_df.to_csv("data/project_data_sample.csv")
merged_df

,photo_id,business_id,caption,label,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours,food
0,pve7D6NUrafHW3EAORubyw,SZU9c8V2GuREDN5KgyHFJw,Shrimp scampi,food,Santa Barbara Shellfish Company,230 Stearns Wharf,Santa Barbara,CA,93101,34.408715,-119.685019,4.0,2404,1,"{'OutdoorSeating': 'True', 'RestaurantsAttire'...","Live/Raw Food, Restaurants, Seafood, Beer Bar,...","{'Monday': '0:0-0:0', 'Tuesday': '11:0-21:0', ...",Shrimp scampi
1,Le9rMdT8YFlvqr431LctIQ,BELS5YkYjDFkpbM2FuDdaA,Fried Chick'un Sandwich,food,Nourish,943 S 9th St,Philadelphia,PA,19147,39.937838,-75.157990,4.5,90,1,"{'NoiseLevel': 'u'average'', 'BusinessAcceptsC...","Food, Juice Bars & Smoothies, Vegan, Breakfast...","{'Monday': '9:0-22:0', 'Tuesday': '9:0-22:0', ...",Fried Chick'un Sandwich
2,9kVdBkGWcKfCFzSwUXjQyw,iryqT-RFwl7erA4MDAuLyg,The Korrito! Korean BBQ sushi made burrito size!,food,Funk Seoul Brother,,Nashville,TN,37214,36.141025,-86.671182,4.0,81,0,"{'BikeParking': 'True', 'BusinessParking': '{'...","Caribbean, Food Stands, Street Vendors, Restau...",None,The Korrito! Korean BBQ sushi made burrito size!
3,e0dD0np3hY3F8LoUtrNoPw,jTFl9Cr7RqZqwjH-CI1ZPw,These cream filled donuts can't be beat! Crea...,food,The Happy Mixer Gluten Free Bakery,4275 County Line Rd,Chalfont,PA,18914,40.265915,-75.224237,5.0,84,1,"{'BikeParking': 'False', 'OutdoorSeating': 'Fa...","Food, Grocery, Restaurants, Bakeries, Gluten-Free","{'Monday': '7:0-18:0', 'Tuesday': '7:0-18:0', ...",These cream filled donuts can't be beat! Crea...
4,xiyqMEgTl4B4ux047E_zqw,Ghn6flCdNlOchzLA29tkjQ,Piedmont Salad--serious yum factor,food,Basso,7036 Clayton Ave,Saint Louis,MO,63117,38.633229,-90.306749,4.0,463,1,"{'RestaurantsAttire': ''casual'', 'Restaurants...","American (New), Bars, Nightlife, Italian, Rest...","{'Monday': '0:0-0:0', 'Tuesday': '16:0-22:0', ...",Piedmont Salad--serious yum factor
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55284,4cI_ZGkzyZnpTlwenTrpFA,wIz_tZ88bj4W3VlrJTiiqQ,Pork belly,food,edison: food+drink lab,912 W Kennedy Blvd,Tampa,FL,33606,27.944244,-82.469306,4.0,848,1,"{'Alcohol': 'u'full_bar'', 'Caters': 'True', '...","American (New), Restaurants, Wine Bars, Beer B...","{'Monday': '17:0-22:0', 'Tuesday': '17:0-22:0'...",Pork belly
55285,TPiBKvLj7WCkk4aR-GGA5g,EYs_T4NU2BbaUF7vUDI55Q,Beauty queen,food,JJ Sushi,"2868 Vista Blvd, Ste 116",Sparks,NV,89434,39.556372,-119.703763,4.0,406,1,"{'Caters': 'False', 'BikeParking': 'True', 'Re...","Sushi Bars, Restaurants, Japanese","{'Monday': '11:0-21:0', 'Wednesday': '11:0-21:...",Beauty queen
55286,hLrcPCLQ8on6VzxIJZdBoQ,9_V0SWbQPnZ0mR3kljXqBQ,The boat always looks so elegant,food,Sakura Japanese Restaurant,1973 Street Rd,Bensalem,PA,19020,40.097353,-74.945416,3.5,254,1,"{'HasTV': 'False', 'NoiseLevel': 'u'average'',...","Restaurants, Sushi Bars, Japanese","{'Monday': '11:0-22:0', 'Tuesday': '11:0-22:0'...",The boat always looks so elegant
55287,n8PcPp6Xyr26KwV06c3XNQ,k1WPGl766RE5t42kD60RyQ,Limoncello cake,food,Luigi's Restaurant,1992 York Rd,Jamison,PA,18929,40.248048,-75.090665,3.5,58,1,"{'BusinessParking': '{'garage': False, 'street...","Italian, Restaurants","{'Monday': '11:0-21:0', 'Tuesday': '11:0-21:0'...",Limoncello cake
55288,4Zia9NkAfQNjMfcIDhwJ-g,2HxkdqHmbYGj_BH1bLaiSw,#Nektar,food,Nektar Wine Bar,8 W Mechanic St,New Hope,PA,18938,40.362115,-74.950957,4.0,353,1,"{'GoodForDancing': 'False', 'OutdoorSeating': ...","Restaurants, Tapas Bars, Mediterranean, Wine B...","{'Monday': '0:0-0:0', 'Tuesday': '12:0-21:0', ...",#Nektar

# LLama Semantic Extract

In [ ]:
class Food(BaseModel):
    food:str

client = ollama.Client(host='http://localhost:11434')

def extract_food(input:str) -> str:
    # 3. Get JSON schema from Pydantic
    schema = Food.model_json_schema()

    response = ollama.chat(
        model='llama3.2',
        messages=[
            {'role': 'system', 'content': 'You are a precise data extraction assistant. Extract information strictly matching the requested schema.'},
            {'role': 'user', 'content': f'Extract information from this text:\n\n{input}'}
        ],
        format=schema, # Enforces JSON matching the Pydantic model
        options={'temperature': 0}
    )

    # 5. Parse and display the result
    resp = json.loads(response['message']['content'])["food"]
    print(resp)
    return resp

cheese pizza

'cheese pizza'

In [29]:
merged_df["food"] = merged_df["caption"].apply(extract_food)
# extract_food("Sometimes I enjoy the Godfather pizza at Roppolios.")

Burritos de Carne Enchilada
Bakery
Açaí Bowls
Sushi
S'mores dessert
Spicy Miso Ramen
Sushi
Strawberry Cheesecake
Tortillas
Toasted Walnut Maple Pie
Vegetarian platter
Fried Giant Squid
Brussels Sprouts
Seafood
House Beef Pho
Poutine Fries
chicken
Asian Chicken Salad
not crispy bacon
FRIES
French toast
Lamb meatball radish soup
None
Mexican Brownie Monster
Bulgogi Poutine
Deviled Eggs
Barbacoa Burrito Bowl
sushi
Mussels
Ahi Tuna Tower
Jumbo Fried Shrimp with French Fries
Chicken Pita
Deep Fried Banana Caramel Cheesecake
Que Rico Chorizo Pizza
Crab and shrimp pizza
Metairie roll
Cinnamon French Toast
Meat
pulled pork and bacon
pizza
pulled pork French fries
Pad Thai
Hand pulled noodle with meat sauce
Plantain chips
None
Vegetable Dumplings
Cupcake Bar & Café
Beignets
chicken arepa
Bahn mi
Wine basket
Nacho's
Spicy Deluxe Sandwich
dosa
Jersey Chips
Mac 'n Cheese
Slaw with peanuts
Bulgogi Burger
Katsu Sandwich
Pistachio ice cream
soup
None mentioned
None
Basil Pesto Agnolotti
BBQ shrimps with baby bok choy
None
Nachos
Petite Filet and Shrimp
Mini Pie
Spicy duck with black sauce and mung bean jelly
Chicken Tikka Marsala
Cioppino
Indianapolis Roll
None
Iced coffee
Cheese platter
Pimento Cheese
none
Pumpkin cream cheese & jalapeño with veggies bagels
steak tacos
Demi God
Devonshire pasty
cake
Tiramisu Affogato Budino
mashed potatoes
Spaghetti & Meatballs
Al pastor burrito
roast beef sandwich
Jerk Chicken
Egg scramble
Taco
shrimps and grits
shrimp rolls
None specified
Teriyaki Chicken & Teriyaki Beef
Green tea custard wheel cake
buffalo chicken
little Caesar
Coconut Shrimp
None
Loco Moco
wine
Grilled Chicken Salad
Pastries
Turkish Delight
Butterfinger Doughnut
16
pizza
Double bacon burger
Manti
baked goods
delicious
Crispy Laad Naarh
Lox
Tagliatelle
None
Chicken Manchurian
Falafel
Coconut HookUp
Soft shell crab
Goat Cheesecake
Salted caramel gelato
cocktail
Cheese Fries
Truffle Mac n Cheese
Bruschetta appetizer
Duk Bae Gi Bulgogi (Bulgogi Soup)
Cold seafood platter
Walnut and Goat Cheese stuffed Chicken
Char Grilled Oyster
Tonion
Asparagus
Juda's Jerk Entrée (1/2 Chicken)
Goat cheese burger, whiskey onion flatbread, crispy brussels
Cinnamon Toast Crunch
Nicey Treats
Cookie
Scallops
burrito bowl
Eel with Rice
Focaccia
untitled
veggie vegan burrito
Color Bowl
tuna
Taiwanese Shaved Ice
Corn and Jalapeño fritters
Banana Foster Crepe
Lamb ribs
Legendary Steaks
wings
buffalo wrap
Island Chicken Quesadilla
Sausage Biscuit
Bun cha Hanoi
Tuna poke
Parfait and Le Veggie
Cajun Shrimp Fried Rice
Original
shrimp dumplings
Waffles, Pancakes
Quesadillas
Karrage rice bowl, jalapeño spam bun, and sour sausage dumplings
Sticky Buns with Nuts
Vegan chocolate, mint chocolate chip, coconut almond fudge, strawberry banana smoothie, butter pecan
Hot Siracha Guacamole
popcorn
MOJARRA
Habit image
Oysters
Bon bon salad
Wiz
oysters
Catering Information
Lobster Ravioli
Roasted pork shoulder
Carne Asada Skillet Breakfast
bbq pork dinner
Bayley Hazen Blue cheese
Caramel and Apple empanada
Tacos
key lime pie
Strawberry Pancake Puppies
Eggs
Chili Cheese
Quesadilla Burger
dipping sauce
Pesce
Pork Cheeks
Braised Wagyu Pappardelle
Fried Shrimp Poboy
Hummus
Camarones Al Ajillo
Shiitake mushroom stuffed tofu
Goat Curry
Brie cheese and mushroom
Eggs Owen
Poop chute
Carajillo Cake
Burger
Triple Double Cheeseburgers, no cheese with Drake's Fries
Crab Spaghetti
grilled chicken breast
Flatbread
Corned Beef Bennie
pork belly quesadilla
Chicken Lebanese
Country Fried Steak
Green Dragon
one egg, one pancake, piece of bacon
Halibut
Hot Chocolate chip
American With
pumpkin
Escargot
Sesame Soft shell crab
Bangkok Thai Burrito
Pork Chop
French onion soup
Matcha Mochi
melt
warm grain bowls, salads & wraps
Lunch Specials
Wagyu beef brisket
Der Kummerspeck
nicahabana hand rolled - real cigars
Chocolate Ganache Cake
snickerdoodles
Cajun Fries
Royale With Cheese
BBQ chicken
Chocolate flan
Stuffed Flatbread
beef schwarma
Pizza
Whiskey Bacon Burger
mochi doughnut
Toast with eggs, avocado & crispy yumm prosciutto
Surf and turf tempura roll
No. 8 Chicken Tender Platter
Shrimp Tacos
Fitz's Milk Shakes
The 12 South
very good
Reuben Burger
Candy
Dungeness Crab Cake & Potato Hash w/Avocado Salsa, Poached Eggs and Lemon Butter Sauce
cheese and egg
None
Seaweed salad
bowl
Yum Yum Roll
Lobster roll
Bourbon-Peppercorn Glazed Meatloaf
Cocktails
stuffed peppers
Spaghetti with fried poached egg
Treats
Cali Club Chicken Sandwich
Buttermilk biscuits with sausage gravy
Cheese Steaks
chicken fingers
cake
Yellowfin Tuna Tartare
Tandoori Chicken Poutine
Italian focaccia
Salad
Chicken Empanadas
wings
garlic noodles
Bananas
pulav
QDOBA
Sinatra Burger
Double Cheeseburger
Empanada De Verde
donair
sweet cream
Duck breast, rice, and smoked carrot puree
Junkyard Fries
Cobb Salad
None
Piatto di legno
Chicken and vegetables
softshell crab appetizer
Sticky Bun French Toast
Entenmann's Bakery Outlet
Latke
Low Country Boil
BBQ Nachos
Chicken & Ribs Combo
King Cake
mushy pimento mac and bean
Mango Milk Tea
Raw Bar
Cheesesteak Hoagie Sub
drink/sweet
torta
breakfast
Classic Cheeseburger
Shrimp insalate
Carnitas Nachos
Veggie Bean
Salmon
Lamb barbacoa
Roast Beef With Cheddar
Cookies
Acai Bowls
Beef Sausage
pâté
Chicken Anna Maria
Pastrami, Brisket, Cheddar Jalapeno Sausage
Breakfast burrito with potatoes
Tortilla Club Sandwich
baked goods
None
Breakfast
Tea
Chocolate fudge sorbet
bread
arrangements
Kanella platter
bowl
Guacamole
Cheese pizza
Mimi Banh mi with an egg
Chocolate Almond Fudge
Truffle croissant
Double Chocolate
slash roll
Raspberry Peach Muffin
Market Vegetables
Yummy
Hakka noodles
Karma Roll JB Tempura Roll
Carnitas Nachos
Empanada Platter
BBQ wings, garlic parmesan wings, fries
Honey bbq wings
Blackened fish po boy
Mediterranean Sea Bass
Garlic Twists
Quesadilla Burger
donut
Brisket Biscuit
Crazy Corn
Su/Sa boat
Bucatini with jalapeno and almond pesto
shrimp
Fried Dumpling
Fries
DimSum Menu
Burrito de pollo
Spanish
Big Bad Breakfast + Biscuit
Romaine shawarma bowl with harissa
Mr. Tso's Cauliflower
Hot Cocoa Cheesecake
chips and salsa
roasted sprouts
Soft shell Fried Soft - shell Crab Platter
Ice Cream
Hot Bag O Donuts
Butter Pecan Brownie Sundae
Shrimp & Chicken Alfredo
Brussels
Grilled Chicken Salad
Hampton
Cinnamon roll and baguette
Dessert Sampler
Stir fry Pork neck
Chicken Satay
Catering Size
Spring roll
Roasted fingerling potatoes, white bean stew, and garbanzo bean salad (which was mostly chickpeas)
chocolate chip pancakes
Cheesecake
Chicken yaki udon
Donuts
Garlic Knots
Porkchops
Collard Green Melt
The Fold
ice cream
Ravioli della casa
Cheesesteaks
Le Luxe Chèvre and a pepperoni pie from Red-L
Albondigas
poke bowl
pita bread
Spicy tuna nigiri
Seared Flat Iron Steak
Salmon Ceviche
cakes
Sushi
Crabcake Sandwich
Roti Canai
Deep fried Oreos
chicken Cobb salad
Cookies and cream gelato
quesadillas
Yellowtail sushi
Carmelized Eggplant Bao Buns
Pād Ke Mow
Torta hawaiana
Halibut Burgers
None
House salad and baked potato
Texas toast
Char grilled oysters
Mac n Cheese
Grilled shrimp salad
Mini Pumpkin Pies
Beef
quesabirria
Tacos
tomato basil omelette
Wedge salad
Caesar with Anchovies
BLT - Bacon, Lobster & Tomato Ravioli
Shrimp Po Boy
Dolmades
Marinated Tofu Quesadilla
None
Horiatiki Salata with Gyro
German Chocolate Cupcakes
Seafood pancake
Klassic Kyle
Thin Crust
Blueberry and lemon curd pound cake with ice cream
Spiced Crab Naan
ketchup packet
Breakfast Nachos
Brisket Sandwich
Parisian Za
Chorizo y Pollo Paella
WINGS
Ham and Swiss broken yolk sandwich, apple fritter cinnamon French toast
Metropolitan Meatloaf
None
Spumoni
Chicken Beryani
Avocado toast
Chicken tikka bowl
sauce
French Dip
The Julius Caesar Greens
Crawfish Etouffee Fries
Guac
None specified
Oysters
Gingerbread Latte
Homestyle Chicken-Fried Steak
Seafood
Fried Macaroni & Cheese
Peg Leg Wings
charcuterie
Tarbush Kitchen LLC
Wild Baby Arugula Salad
Carnitas
Jerk chicken
House Salad
Cauliflower bites
Dirty Kettle Chips
squid
Sushi
Baked Drum
beef
Chicken kabob
GREEK WRAP
Dutch Pancake
Pastrami sandwich
BBQ
Egg rolls
Blackened Jambalaya
Chocolate Truffle Cake
canned
Grass Fed Beef Taco Kit With Salsa Verde (6 Tacos)
The Original Steakburger
Peach and blueberry cobbler
tacos
Shrimp Fried Rice
scrambled eggs
LongHorn porterhouse
None
Flourless chocolate cake
Fried oyster
Beef fried rice
eggs in a basket
Chicken lasooni
Turkey Wing, Fried Chicken, Mac-n-cheese, Mashed Potatoes, Roll
Ube milkshake
Hamachi Tiradito
MEAT LASAGNA
pork steak
buffalo wings
Rigatoni Bolognese
Strawberry Pancake Puppies
Chicken Porridge
Oatmeal peanut butter cookie
foreign country experience
Leek and Black Trumpet Mushroom Terrine
deep fried pork bellies
escolar sashimi
Baklava
French toast waffle
Onion rings
Chicken Salad Sandwich
Shrimp Tempura
Burrata
Pancakes
Grilled Veggies
Escargots
Cotton Candy
Chile Margarita
Chicken Tikka Masala
Fried alligator
chicken bites
None
sushi
Homemade Meat Lasagna
Spirulina bowl
Cheng Duck Dumpling
assortment
Macaroni
chicken
Katlama bread
Eggplant&shrimp stack
toast
Walnut Ginger Streusel Pie
Crab stuffed peppers
Sliders
Chicken banh mi
Island Way Burger and Fries
Dip
cookies
strawberry churro
Wagyu Beef Brisket
lamb stew
King Crab Leg
Awesome-burger and fries
Atlantic salmon
none
Crispy Whole Local Snapper
Sicilian Cheesecake
garlic knots
Arroz Con Mariscos
Hot Chocolate
Veggie tempura
Muffaletta
Salmon carpaccio
Chicken Khorma
Prawns
xiaolongbao
dried florals
Caprese bagel
Mac and cheese
Fries
dessert
Mango and Jicama Salad
none
Eggs Florentine Benedict
Seafood Gumbo Shrimp and Crab with rice
Mozzerella Stick Grilled Cheese Sandwich
Salad
Brisket Taco
Bacon Burger
Chicken nuggies
Fried Green Tomatoes
pizza
Peanut Butter Pie
Avocado Toast
Sandwich
Grilled hanger steak with corn machoux
tacos
White Chicken Chili
Roasted Ginger Honey Duck
Salmon Draniki
Pad Pui Wan Chicken
B.O.B. Deluxe
Smoked salmon
Fresh spring rolls
Kids meal salad
Gôi Cuon Chay
Red Beet tartare
Pretzel
Wings
chocolate cake
Golden Crispy
None
Caprese sandwich
Chipotle Garlic Shrimp Two Taco Plate
Strawberry Milkshake
burger
Sicilian Cheesecake
Beer Flight & Flatbread
Chicken Teriyaki with Rice
Happy Hour Nachos
Chargrilled Oysters
Burger and fries
Grand Slam
Sera Scallops & Shrimp
Breakfast
Punch Burger
Brisket and chicken
Apple fritter, cinnamon roll, cinnamon cheesecake, and pink sprinkle
Chicken Cheesesteak
meaty
Strawberry Salad
Pulled Pork Barbeque
New York Strip steak
steak
Cinnamon roll baklava
tea
Fries
Butter croissant
chicken sandwich
Pavlova
Crispy Southern Chicken
Mozzarella Sticks
Pesto
Brioche
Phyllo Wrapped Sea Bass
Chocolate ice cream
beignets
Hot chicken
burger
Pescado Miranda
Octopus dish
Duck fat fries
Empanadas
Cobb Salad
Mac and cheese pizza, Seafood chowder and lobster Penne Pasta
Cares salad
gobi manchuria
Combo pork meat balls, grilled lemongrass pork & spring rolls
Rainbow cookie
Smoked Shrimp and Spring Onion Bisque
Tres leche phenomenal
Brisket sandwich and corn fritters
Chips and guacamole
Milk and Cereal
Roll
Roasted Ravioli
Everything But...
Chipotle Lime
veal piccata
bacon and scrambled eggs
Grilled Pork Chop w/Peaches
Hawaiian chicken
Tiramisu
Zucchini fries
Burrata and Pesto Salad
Dessert Trio
Grilled Salmon
Chicken Bowl
Golden Beet Salad
dinner at the wedge and fig
Ricotta Corn dip
Apple Pomme
Brussels Sprouts
Sundae
Green Eggs and Ham Breakfast Sandwich
Chicken Tenders Platter
Royale with Cheese
Rack of lamb
Hong Kong BBQ Pork Chow Mein
Apple Cider Pork Belly Hash
Mini dark chocolate cakes
None
Seitan cheesesteak
Hamburguesa Torta
Beef shawarma scallops shish kabob
latte
Curried Chicken Salad
tasting menu
New York style pizza
Ichiban Roll
Spanokapita
Cranberry Orange Scones
TAP roll
Zucchini Pancakes
Strawberry Lemon
Kebab
Spicy chicken ramen
Ribs
Charbroiled Oysters
barbecue dry rub wings
None
Lobster
Atlantic Salmon
Noon Mediterranean
Honeys Pancakes
None
Fried Chicken Skin
Margherita pizza with added capocollo
Eggs Florentine
Tomato Bisque
Raw bar
wood fired pizza
Country Fried Steak
White Gourmet Pizza
Porkchop chicken noodle soup
Avocado & Garbanzo Southwest Bowl
Salmon Sashimi
tenders
Beef Brisket
Hickory Bacon Cheddar Burger
Pizzette Pizza
Yeast Rings
double spicy pepperoni & banana peppers
Hummus
gluten free
EdgeWild Edwardsville
Shwarma Fries
Chicken
Bibimbap
Buttermilk & Appalachian Apple Butter (Seasonal)
Nachos
tater tots
Chocolate Chip Muffin
Spaghetti
Egg over easy bacon & toast
Mediterranean chicken
Shrimp Po Boy
finger foods
None
oysters
Chirashi Hokkaido
Vietnamese Crepe
Heritage Raised Pork Tenderloin
Grande Toasted Breakfast Burrito Bacon
Acadian pearl oysters with pickled local rhubarb
Sakura
Pizza
Tomato Pie
Banana Split
S'mores
Fried Dumplings
chocolate cake
Hot mezza
Smoothie
Fajitas
BBQ Chicken
Turkey and herb sandwich with gazpacho
Bolognese
cheesesteak
Buffalo chicken tenders
Swordfish
Veggie pizza
82 Degrees House Salad
Brussel sprouts
Doughnuts
oyster PoBoy
strawberry cheesecake
ARROZ CON POLLO
South Indian pancake
Sangria and salsa
Ceviche
Cod fish Ceviche
Holey Donuts
Grilled pork and egg roll rice
Cruzan Rum
Chapati's twist on Pakistani & Indian street food
salad
Breakfast of Champions milkshake
Sea Green Salad
Spicy salmon roll & spicy rainbow roll
Chargrilled oysters
Turkey BLT
Chicksilog or Grilled chicken
Larb Kai
Calazone
Mahi
Chicken Shawarma Platter
Naruto
Crepe
Steaks
Oysters
Wedding cake
Pork barbecue with spicy vinegar
Donut
cookie
pizzas
tea
Red Beans & Rice
chicken parmesan
Bottle of Prosecco & Calamari
dining
Lama burger
Conch/Shrimp/Crab/Lobster
PARRILLADA 6 DIFFERENT MEAT WITH RICE BEANS GUACAMOLE AND SALAD
meat lovers omelette
None
Elevated Eggs
Turkey, brie, spiced apple crepe
Chicken skewers
Whiskey Bacon Burger
Grilled boudin
Irish 31 Grilled Vegetable Balsamic Salad
3-cheese queso
Breakfast
Dozen Chargrilled Oysters
Cinnamon Roll French Toast
Milaneza De Pollo
Ribs
Clear Soup
Angels Spicy Omlette
Tiger eyes
Taco
Combo
None
Cheesecake
Cheese Pizza
Seaside Platter
American Cheese Plate
Carne Asada Taco
White
Filet mignon
Sweet Chili Chicken Pizza
Bagel w/ Cream Cheese
Grilled Shrimp
Banana Chocolate Hazlenut Crepe Breakfast
Shrimp Grilled Cheese
Softshell Crab
Vegan Wings
Fried Green Tomato
Lobster Roll
Beet Salad
Strawberry Lavender Creme
Tres leches cake
Chicken & Provolone Sandwich
pizza
shrimp
Hot stone b-bim-bap
Safari Animal Birthday Cake
filet mignon
Buffalo Chicken Wings
banana pudding
Ube and pandan ice cream
steak
Bella Pizza
drink
Reese's PB Awesome Sauce
None
Super fresh, locally sourced beef, some cheese, bacon, an onion ring
Jambon beurre
Kale Salad
Naan
Tacos Al Carbon
Apple Turnover
Dessert Trio
Turkey Hoagie
biscuits
Buffalo Chicken Sandwich
Shoyu Ramen
Kabob Meals
Pepperloin
Cheese plate
Sushi-Kito Roll
pizza
Duck fat fries
Cookie butter and Carmel turtle fudge on a waffle cone
Fried Chicken Sandwich
Beignets
cheesy taters
Tuna
crunchy
Kale Caesar Salad
Chipotle Alfredo with Chicken
salad
Side Ceasar
Triple Cream Formage
oysters
Fire Dragon roll
Lychee Panna Cotta, Strawberry Fresh Cream, & Milk Foam Tea
cheese platter
Duck Fat Tater Tots
Tableside Guac & Queso
pizza,pasta,homemade,authentic,lasagna,eggplant parm,chicken parmesan,marsala,calamari
sea soup
salads
green tea chiffon
Tamarind pork shank
Blood Orange Creme Brûlée
Blondie
oysters
olives
Rainbow Roll
Onion Soup (au gratin)
None
KY Kelsey Brown
Club Sandwich
Grilled Salmon
Supreme with extra cheese
chicken chunks
Grape Leaves
Spinach, basil, tomato & feta omelet
Cheese Crisp
LongHorn porterhouse
Buffalo Chicken Pita
Caramel cheesecake cookie
Sushi
Chicken Quesadilla
King Cake
Chicken Parm Noodles
TS Burrito
Beignets
None
Seafood platter
Linguine Con Vongole
Paradiso
ground lamb
pulled pork with sweet potato
Quesadilla with potato salad
none
Hog Wild Sampler
ghee roast dosa
Charlie Gitto's On the Hill
Knuckle Sandwich
Cowboy BBQ Burger
Med plate
Greek Salad with chicken
Chicken Spinach Mozzarella
Brisket
Chicken Shawarma salad
Bananas Florentine
Buffalo Chicken Wrap
wings
gelato
Pork belly Potstickers
sushi roll
Truffle Risotto
Roast duck
Atlantic salmon
Chicken Shawarma Sandwich
pickled veg
Tiramisu
Topped Grilled Chicken
1905 salad
fries
BEETS
sirloin
Pate encroute
Chicken & Waffles
Bruschetta
Apple caramel french toast
rice and beans
Rigatoni
Skillet
Frozen citrus salad
dinner
Hamburger Flatbread
No specific information provided
Black beans over rice
Kwek-kwek & fishball
MOMO
burrito
oily residue
maitake mushroom w/ celery root fritter
burger
Parsley potatoes
Yum!!
Margarita Pizza
cake
Granny Apple Smith
brunch
Bombay Drum
Volcano Bay signature roll
Puff Puff
Smoked petuna trout
Lamb Shank
chocolate
Pho Thailand (Spicy)
chocolate chip cookies
Spicy popcorn chicken and waffle fries
Bacon
Chicken Tikka Masala
Dan's Omelet
Little Lion Burger
@nomtasticfoods
Ranch Fries
Matcha Milky Flurry
Ribs
Boston Market Half Chicken Dinner
Philly Cheesesteak Eggrolls
blue cheese crumbles
Beef Tataki
Wings
Chaoshou Dumplings
brunch
Pad Kra Pao
Chimichanga
Godzilla Roll
Tea
Caramel frappe
Pina Colada
Al Pastor Nachos
tiger skin
Bacon Mac Pasta
Tobiko with Quail Egg
Italian Stallion
Chicken Parm with Penne
Pork Tenderloin
Krupak and Sambal
peanuts
scone
Mushroom Pizza
cantaloupe
Panang Curry
Amazing
Lobster Roll
Lemon Ricotta Pancakes
cupcake
Moules Provencal Frites and Saffron Risotto
Island Green Smoothie and Thai Chicken Bowl
Oreo pancake
Frankie Fathers Day Benedict
tuna salad
Lobster baked potato
basil
Stone CRAB
Pizza
Candied Bacon
bacon
Super Crunch
None
China Garden
Ice cream sandwich bao
Nashville Chix Sandwich
Steak and Eggs
deviled eggs sampler
French Dip Sandwich
carrot cake
Red fish
Omelette
Rolls
Broth
Rice bowl
Chutneys
bouillabaisse
Beignets
sauces
hot pot
spaghetti meatballs
Smooth Chocolate Velvet
Chicken Cacciatore
Sunomono Salad
Chocolate Dipped Indulgence Platter
Hummus, baba ghanouj, Tzaziki
brunch
Matcha Chocolate Truffles Crepe
Rockefeller
Andouille Sausage Sandwich
biscuits
Potato-Crusted Blue Point Oysters
Housemade potato and vegetable soup
Buffalo Chicken Pizza
Hot wings
Botan Kabob
Twinkie Ice Cream
Goat cheese and bacon omelette
Sweet Potato Desserts
Masala dosa
Junior burger
Biscotti's Melt
Queso Rollies
Pambazo de Papa con Chorizo
Greek Bruschetta
Burrito bowl
Rock & Roll // Threesome Roll
crepes
Delicious
Fried Chick'un Sandwich
夫妻肺片
Grand Slam
Fried Ice Cream
Unagi Ishiyaki
Guac
Red Lentil Soup
egg omelette
crawfish
Combo
Chicken Inasal Silog
Bonuts
Chicken Andouille Pogirl
cake
Meat Lasagna
gumbo
BBQ Beef and Mac n' Cheese
Cacao-nut Bowl
CHICKEN KARAAGE
Cowboy BBQ Burger
Tavern Club
grits
Poke salad
Burger
ice cream
Empanadas
FLAUTAS
Fries
Frutti di Mare
pizza
Snow crab legs
Strawberry Pancake Puppies
Burnt Ends
Louisiana Fried Catfish
Spicy Tuna, Philadelphia, and Rittenhouse roll
bread
Golden Fried Shrimp Po'boy
Whipped Foie Gras au Torchon
duck
None specified
mussels and fries
Fresella
That Sweet Burn Roll
Cinnamon Roll French Toast
Farro Vegetable Soup
FAJITAS QUE PASA!
Chicken and waffle with mixed fruit
Honey Nut Sweet Potato Fries
Blueberry scone
Fruit tart
Singapore noodles
Spicy Tuna Crunchy
gummy bear
homestyle fries
Bread pudding
None
Almond Milk, Coconut Milk, Pineapples, Banana
Nicey Treats
Pizza
burger
Sandwiches
Spaghetti Squash Casserole
Scallops
Rigatoni and Short Rib Ragu
Rutabaga fondue and tomato on toast
Birthday Cake Milkshake
steak enchiladas verdes with eggs on top
Fatty B
Family Meal
Tuna
Chicken Teriyaki lunch
Hachapuri Pie
Spätzle poutine
Beef combo
burrito bowl
BLT Classic
donuts
Pasta & Bean Soup
Spicy basil fried rice
ribs
Shrimp and KFC baos
Dark chocolate soufflé with chocolate bourbon cream sauce
Meatball Sub
Pimento Cheese Nachos
Lamb Shank Provenal and Steak Au Poivre
Seafood Cioppino with Pasta Capellini
Beignets
Blackened Salmon
Chop Chop Salad
Avocado Toast (actually a bagel)
salmon
Basque cheesecake
Homemade Chocolate Chip Cheesecake
Charbroiled Oysters
yellowtail tartare
Totchos
Guacamole, beef and sea bass taco (recommend both) and red snapper

# Semantic Extraction Concurrently

In [24]:
DQ = deque(["api 1", "api 2", "api 3"])

class Food(BaseModel):
    food:str

client1 = ollama.Client(host='http://localhost:11434')
client2 = ollama.Client(host='http://localhost:11435')
client3 = ollama.Client(host='http://localhost:11436')

DQ = deque([client1, client2, client3])

def extract_food(input:str, client:ollama.Client) -> str:
    # 3. Get JSON schema from Pydantic
    schema = Food.model_json_schema()

    response = client.chat(
        model='llama3.2',
        messages=[
            {'role': 'system', 'content': 'You are a precise data extraction assistant. Extract information strictly matching the requested schema.'},
            {'role': 'user', 'content': f'Extract information from this text:\n\n{input}'}
        ],
        format=schema, # Enforces JSON matching the Pydantic model
        options={'temperature': 0}
    )

    # 5. Parse and display the result
    resp = json.loads(response['message']['content'])["food"]
    print(resp)
    return resp

def concurrent_llama_api(image_desc:str) -> str:
    client = DQ.popleft()
    extract_food(image_desc, client)
    time.sleep(.1)
    DQ.append(client)

def semantic_extraction_concurrently(df: pd.DataFrame):
    with ThreadPoolExecutor(max_workers=3) as executor:
        df['result'] = list(executor.map(concurrent_llama_api, df['food']))

# Seed the Database

In [75]:
from pydantic import BaseModel, Field, ValidationError
from sqlalchemy import create_engine, Boolean, Column, Integer, String, Double, select
import mysql
from mysql import connector
from mysql.connector import Error
from sqlalchemy.orm import sessionmaker, Session
from sqlalchemy.ext.declarative import declarative_base

URL_DATABASE = 'mysql+pymysql://root:password1234!@localhost:3333/TealDB'
engine = create_engine(URL_DATABASE)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()

C:\Users\samfg\AppData\Local\Temp\ipykernel_36640\347753760.py:12: MovedIn20Warning: The ``declarative_base()`` function is now available as sqlalchemy.orm.declarative_base(). (deprecated since: 2.0) (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
  Base = declarative_base()

In [46]:
def create_database(db_name: str) -> None:
    try:
        connection = connector.connect(
            host="localhost",
            user="root",
            password="password1234!",
            port=3333
        )
        if connection.is_connected():
            cursor = connection.cursor()
            cursor.execute(f"CREATE DATABASE IF NOT EXISTS {db_name}")
            print(f"Database '{db_name}' created successfully!")
    except Error as e:
        print(f"Error while connecting to MySQL: {e}")
    finally:
        if 'connection' in locals() and connection.is_connected():
            cursor.close()
            connection.close()

create_database("TealDB")

Database 'TealDB' created successfully!

In [58]:
class BusinessSchema(Base):
    __tablename__ = 'business'
    business_id: str = Column(String(50), primary_key=True)
    name: str = Column(String(100))
    address: str = Column(String(120))
    city: str = Column(String(50))
    state: str = Column(String(2))
    postal_code: int = Column(Integer)
    latitude: float = Column(Double)
    longitude: float =Field(Double)
    stars: int = Field(Double)
    review_count: int = Field(Integer)
    categories:str = Column(String(120))

class FoodSchema(Base):
    __tablename__ = 'food'
    business_id: str = Column(String(50), primary_key=True)
    photo_id: str = Column(String(50))
    caption: str = Column(String(200))
    food: str = Column(String(75))

#Create the tables in MYSQL DB
Base.metadata.create_all(bind=engine)

# Populate Datatables

In [68]:
merged_df.to_csv('data/project_data.csv', index=False)
print(merged_df.columns)

Index(['photo_id', 'business_id', 'caption', 'label', 'name', 'address',
       'city', 'state', 'postal_code', 'latitude', 'longitude', 'stars',
       'review_count', 'is_open', 'attributes', 'categories', 'hours', 'food'],
      dtype='object')

In [69]:

food_df = merged_df[["photo_id", "business_id", "caption", "food"]]
business_df = merged_df.drop(columns=["photo_id", "caption", "food", "is_open", "attributes", "hours"])
food_df.to_sql(
    name="food",
    con=engine,
    if_exists="replace"
)
business_df.to_sql(
    name="business",
    con=engine,
    if_exists="replace"    
)

2000

# Mission

- *Orchestrate MYSQL, Fast API, and Ollama with Docker Compose
- *Filter out any '\n' from data, combine american traditional and new*
- Create Dashboard of most common type of cuisine by category 'like syntax' (Donut Chart)
- Showcase Number of Reviews by Cusine category (Bubble Chart)
- List of Results of food items per selected category 
- Geographic locations size by user_review|businesses
- Food items Stream Graph by Category or Spyder Graph *Create 10k from target categories, semantic extract with ollama, create new datatable with them*
- ?Most photographed cuisine by State

In [52]:
from collections import Counter
import re

In [86]:
df = pd.read_csv('data/project_data_sample.csv')
# df.to_csv('data/project_data_sample.csv', index=False)
df.head()
df.size

995202

In [55]:
def retrieve_category_map(df: pd.DataFrame) -> dict:
    """Filter and Extract all unique values for business categories of food data"""
    df['categories'] = df['categories'].apply( lambda x: re.sub(r'\s*,\s*', ',', x).lower() )
    return df['categories'].str.split(',').explode().value_counts().to_dict()

def filter_target_cuisine_types(hashmap:dict, targets:list) -> dict:
    """Sort out category types that are not cuisines or too general"""
    return {key: val for key, val in hashmap if key in targets}

In [58]:
#Iterate through categories, reviews. Iterate through counter. If categories has topic from target list add Reviews
def retrieve_user_cnt(df: pd.DataFrame, target:str) -> int:
    """Sum the number of user reviews for business who have a particular category"""
    return int(df[df['categories'].str.contains(target, case=False)]['review_count'].sum())


review_count = Counter()
review_count = Counter({key: retrieve_user_cnt(df,key) for key in category_map.keys()})
review_count

Counter({'vegan': 642614, 'caribbean': 176952})

In [ ]:
def retrieve_n_food_items(df:pd.DataFrame, cuisine:str, num_foods:int=10) -> list:
    """Retrieve a sample of food items per cuisine"""
    food_df = df.loc[df['categories'].str.contains(cuisine, case=False)]['food']
    food_df = food_df.sample(frac=1)
    return food_df.iloc[0:num_foods].to_list()
retrieve_n_food_items(df=df, cuisine="vegan")

['Truffle Mac N Cheese - delicious!',
 'Pumpkin spice roll',
 'Creole stuffed zucchini',
 '$2.00 Tacos every Taco Tuesday',
 'Kani salad',
 'Mysore masala dosa',
 'Herbivore Plate \nGrilled onion\nFresh avocado \nFresh tomatoes \nSavory sauce',
 'Baklava',
 'Lasagna Bolognese',
 'Certified organic goodness!']

In [ ]:
#Group records by city, state and then retrieve their aggregated user review count
def geo_loc_by_reviews(df:pd.DataFrame) -> dict:
    """Retrieve sum of user reviews by geo location"""
    review_city_cnt = df.groupby(["city","state"])["review_count"].sum()
    return { (", ").join(key): val for key, val in review_city_cnt.to_dict().items() }

def geo_loc_by_business(df:pd.DataFrame) -> dict:
    """Retrieve a count of businesses that exist by geo location"""
    business_city_cnt = df.groupby(["city","state","business_id"])["review_count"].count()
    return { (", ").join(key[0:2]): val for key, val in business_city_cnt.to_dict().items() }


#geo_loc_by_business(df)
review_map = geo_loc_by_reviews(df)
review_cnt = Counter(review_map).most_common(10)
review_cnt

[('New Orleans, LA', 7671129),
 ('Philadelphia, PA', 4343983),
 ('Nashville, TN', 2106327),
 ('Tampa, FL', 1693100),
 ('Santa Barbara, CA', 1449722),
 ('Indianapolis, IN', 884319),
 ('Reno, NV', 755793),
 ('Tucson, AZ', 624798),
 ('Saint Louis, MO', 602031),
 ('Saint Petersburg, FL', 200872)]

In [ ]:
CUISINE_TARGETS  = ['american (new)',
                    'american (traditional)',
                    'seafood',
                    'italian',
                    'coffee & tea',
                    'mexican',
                    'japanese',
                    'asian fusion',
                    'cajun/creole',
                    'chinese',
                    'vegetarian',
                    'southern',
                    'barbeque',
                    'mediterranean',
                    'vegan',
                    'juice bars & smoothies',
                    'french',
                    'thai',
                    'delis',
                    'latin american',
                    'korean',
                    'middle eastern',
                    'indian',
                    'vietnamese',
                    'food trucks',
                    'greek',
                    'donuts',
                    'tex-mex',
                    'ramen']

In [ ]:

class DataEngineering():
    def __init__(self):
        pass

    def retrieve_category_map(self, df: pd.DataFrame) -> dict:
        """Filter and Extract all unique values for business categories of food data"""
        df['categories'] = df['categories'].apply( lambda x: re.sub(r'\s*,\s*', ',', x).lower() )
        return df['categories'].str.split(',').explode().value_counts().to_dict()

    def filter_target_cuisine_types(self, hashmap:dict, targets:list = CUISINE_TARGETS) -> dict:
        """Sort out category types that are not cuisines or too general"""
        return {key: val for key, val in hashmap if key in targets}

    def retrieve_user_cnt(self, df: pd.DataFrame, target:str) -> int:
        """Sum the number of user reviews for business who have a particular category"""
        return int(df[df['categories'].str.contains(target, case=False)]['review_count'].sum())

    def retrieve_n_food_items(self, df:pd.DataFrame, cuisine:str, num_foods:int=10) -> list:
        """Retrieve a sample of food items per cuisine"""
        food_df = df.loc[df['categories'].str.contains(cuisine, case=False)]['food']
        food_df = food_df.sample(frac=1)
        return food_df.iloc[0:num_foods].to_list()

    def geo_loc_by_reviews(self, df:pd.DataFrame) -> dict:
        """Retrieve sum of user reviews by geo location"""
        review_city_cnt = df.groupby(["city","state"])["review_count"].sum()
        return { (", ").join(key): val for key, val in review_city_cnt.to_dict().items() }

    def geo_loc_by_business(self, df:pd.DataFrame) -> dict:
        """Retrieve a count of businesses that exist by geo location"""
        business_city_cnt = df.groupby(["city","state","business_id"])["review_count"].count()
        return { (", ").join(key[0:2]): val for key, val in business_city_cnt.to_dict().items() }

In [ ]:

with Session(engine) as session:
    stmt = select(FoodSchema)
    users = session.scalars(stmt).first()

In [ ]:
users.business_id

'Np9avSrZUn4YInhN-3Pibg'

In [ ]:
for

TypeError: type() argument after * must be an iterable, not FoodSchema

#